POST http://localhost:8080/api/message/START?businessKey=1
Content-Type: application/json

{"var":"val"}
###
POST http://localhost:8080/api/message/CANCEL?businessKey=1
Content-Type: application/json

{"var2":"val2"}
###
POST http://localhost:8080/api/message/ERROR?businessKey=1
Content-Type: application/json
###
POST http://localhost:8080/api/message/NEXT?businessKey=1
Content-Type: application/json

{"var3":"val3"}
###
POST http://localhost:8080/api/message/NEXT_1
Content-Type: application/json
###
POST http://localhost:8080/api/message/UPDATE_SUBPROCESS?businessKey=1
Content-Type: application/json

{"property":"value"}
###
POST http://localhost:8080/api/message/UPDATE_SUBPROCESS_2?businessKey=1
Content-Type: application/json

{"property":"value"}
###
POST http://localhost:8080/api/message/BACK?businessKey=5
Content-Type: application/json

{"var3":"val3"}
###
POST http://localhost:8080/api/message/UPDATE?businessKey=1
Content-Type: application/json

{"var3":"val3"}
###
POST http://localhost:8080/api/external-task/fetchAndLock
Content-Type: application/json

{
  "workerId":"aWorkerId",
  "maxTasks":2,
  "usePriority":true,
  "topics":
  [{"topicName": "decision",
    "lockDuration": 100,
    "variables": []
  }]
}
###
POST http://localhost:8080/api/external-task/27/complete
Content-Type: application/json

{
  "workerId": "aWorkerId",
  "variables":
  {"aVariable": {"value": "aStringValue"},
    "anotherVariable": {"value": 62},
    "aThirdVariable": {"value": true}},
  "localVariables":
  {"aLocalVariable": {"value": "aStringValue"}}
}
###
